src/ProjectBundle/Entity/Banner.php
<?php

namespace ProjectBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * Banner
 *
 * @ORM\Table(name="banner")
 * @ORM\Entity(repositoryClass="ProjectBundle\Repository\BannerRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Banner
{
    use ORMBehaviors\Translatable\Translatable;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     */
    private $image_mobile;

    /**
     * @ORM\Column(name="public_date", type="date", nullable=true)
    */
    private $publicDate;

    /**
     * @ORM\Column(type="smallint")
     */
    private $status = 1;

    /** @ORM\Column(name="updated_at", type="datetime", nullable = true) */
    private $updatedAt;

    /** @ORM\Column(name="created_at", type="datetime") */
    private $createdAt;

    /**
     * @ORM\Column(type="smallint")
     */
    private $position = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable = true)
     */
    private $video;
    /**
    * @ORM\Column(name="video_id", type="string", length=255, nullable = true)
    */
    private $videoId;
    /**
     * @ORM\Column(name="video_width", type="smallint", nullable = true)
     */
    private $videoWidth;
    /**
     * @ORM\Column(name="video_height", type="smallint", nullable = true)
     */
    private $videoHeight;
    /**
     * @ORM\Column(name="video_duration", type="smallint", nullable = true)
     */
    private $videoDuration;
    /**
    * @ORM\Column(name="thumbnail_url", type="string", length=255, nullable = true)
    */
    private $thumbnailUrl;
    /**
     * @ORM\Column(name="thumbnail_width", type="smallint", nullable = true)
     */
    private $thumbnailWidth;
    /**
    * @ORM\Column(name="thumbnail_height", type="smallint", nullable = true)
    */
    private $thumbnailHeight;
    /**
    * @ORM\Column(name="thumbnail_url_play_button", type="string", length=255, nullable = true)
    */
    private $thumbnailUrlPlayButton;
    /**
    * @ORM\Column(name="video_embed", type="text", length=65535, nullable = true)
    */
    private $videoEmbed;

    /**
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps()
    {
      $this->setUpdatedAt(new \DateTime('now'));
      if ($this->getCreatedAt() == null) {
        $this->setCreatedAt(new \DateTime('now'));
      }
    }

    public function __call($method, $arguments)
    {
        return $this->proxyCurrentLocaleTranslation($method, $arguments);
    }

    /**
     * Get the value of Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Id
     *
     * @param int id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of Image
     *
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set the value of Image
     *
     * @param mixed image
     *
     * @return self
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }
    public function removeImage()
		{
			$this->setImage(null);
		}

    /**
     * Get the value of Image Mobile
     *
     * @return mixed
     */
    public function getImageMobile()
    {
        return $this->image_mobile;
    }

    /**
     * Set the value of Image Mobile
     *
     * @param mixed image_mobile
     *
     * @return self
     */
    public function setImageMobile($image_mobile)
    {
        $this->image_mobile = $image_mobile;

        return $this;
    }
    public function removeImageMobile()
	{
		$this->setImageMobile(null);
	}

    /**
     * Get the value of Public Date
     *
     * @return mixed
     */
    public function getPublicDate()
    {
        return $this->publicDate;
    }

    /**
     * Set the value of Public Date
     *
     * @param mixed publicDate
     *
     * @return self
     */
    public function setPublicDate($publicDate)
    {
        $this->publicDate = $publicDate;

        return $this;
    }

    /**
     * Get the value of Status
     *
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set the value of Status
     *
     * @param mixed status
     *
     * @return self
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get the value of Updated At
     *
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set the value of Updated At
     *
     * @param mixed updatedAt
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get the value of Created At
     *
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set the value of Created At
     *
     * @param mixed createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get the value of Position
     *
     * @return mixed
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set the value of Position
     *
     * @param mixed position
     *
     * @return self
     */
    public function setPosition($position)
    {
        $this->position = $position;

        return $this;
    }


    /**
     * Get the value of Video
     *
     * @return mixed
     */
    public function getVideo()
    {
        return $this->video;
    }

    /**
     * Set the value of Video
     *
     * @param mixed video
     *
     * @return self
     */
    public function setVideo($video)
    {
        $this->video = $video;

        return $this;
    }

    /**
     * Get the value of Video Id
     *
     * @return mixed
     */
    public function getVideoId()
    {
        return $this->videoId;
    }

    /**
     * Set the value of Video Id
     *
     * @param mixed videoId
     *
     * @return self
     */
    public function setVideoId($videoId)
    {
        $this->videoId = $videoId;

        return $this;
    }

    /**
     * Get the value of Video Width
     *
     * @return mixed
     */
    public function getVideoWidth()
    {
        return $this->videoWidth;
    }

    /**
     * Set the value of Video Width
     *
     * @param mixed videoWidth
     *
     * @return self
     */
    public function setVideoWidth($videoWidth)
    {
        $this->videoWidth = $videoWidth;

        return $this;
    }

    /**
     * Get the value of Video Height
     *
     * @return mixed
     */
    public function getVideoHeight()
    {
        return $this->videoHeight;
    }

    /**
     * Set the value of Video Height
     *
     * @param mixed videoHeight
     *
     * @return self
     */
    public function setVideoHeight($videoHeight)
    {
        $this->videoHeight = $videoHeight;

        return $this;
    }

    /**
     * Get the value of Video Duration
     *
     * @return mixed
     */
    public function getVideoDuration()
    {
        return $this->videoDuration;
    }

    /**
     * Set the value of Video Duration
     *
     * @param mixed videoDuration
     *
     * @return self
     */
    public function setVideoDuration($videoDuration)
    {
        $this->videoDuration = $videoDuration;

        return $this;
    }

    /**
     * Get the value of Thumbnail Url
     *
     * @return mixed
     */
    public function getThumbnailUrl()
    {
        return $this->thumbnailUrl;
    }

    /**
     * Set the value of Thumbnail Url
     *
     * @param mixed thumbnailUrl
     *
     * @return self
     */
    public function setThumbnailUrl($thumbnailUrl)
    {
        $this->thumbnailUrl = $thumbnailUrl;

        return $this;
    }

    /**
     * Get the value of Thumbnail Width
     *
     * @return mixed
     */
    public function getThumbnailWidth()
    {
        return $this->thumbnailWidth;
    }

    /**
     * Set the value of Thumbnail Width
     *
     * @param mixed thumbnailWidth
     *
     * @return self
     */
    public function setThumbnailWidth($thumbnailWidth)
    {
        $this->thumbnailWidth = $thumbnailWidth;

        return $this;
    }

    /**
     * Get the value of Thumbnail Height
     *
     * @return mixed
     */
    public function getThumbnailHeight()
    {
        return $this->thumbnailHeight;
    }

    /**
     * Set the value of Thumbnail Height
     *
     * @param mixed thumbnailHeight
     *
     * @return self
     */
    public function setThumbnailHeight($thumbnailHeight)
    {
        $this->thumbnailHeight = $thumbnailHeight;

        return $this;
    }

    /**
     * Get the value of Thumbnail Url Play Button
     *
     * @return mixed
     */
    public function getThumbnailUrlPlayButton()
    {
        return $this->thumbnailUrlPlayButton;
    }

    /**
     * Set the value of Thumbnail Url Play Button
     *
     * @param mixed thumbnailUrlPlayButton
     *
     * @return self
     */
    public function setThumbnailUrlPlayButton($thumbnailUrlPlayButton)
    {
        $this->thumbnailUrlPlayButton = $thumbnailUrlPlayButton;

        return $this;
    }

    /**
     * Get the value of Video Embed
     *
     * @return mixed
     */
    public function getVideoEmbed()
    {

src/ProjectBundle/Resources/views/Lazboy/Main/_banner_ad_page.html.twig
{% if banner_ad %}

    {% if banner_ad.image %}
        {% set ads_home_pc = banner_ad.image %}
    {% else %}
        {% set ads_home_pc = '' %}
    {% endif %}
    {% if ads_home_pc %}
        {% set link = banner_ad.getWebsite %}
        {% if link %}
            <a href="{{link}}"><img src="{{ads_home_pc}}" class="w-100 pc" /></a>
        {% else %}
            <img src="{{ads_home_pc}}" class="w-100 pc" />
        {% endif %}
    {% endif %}

    {% if banner_ad.imageMobile %}
        {% set ads_home_m = banner_ad.imageMobile %}
    {% else %}
        {% set ads_home_m = ads_home_pc %}
    {% endif %}
    {% if ads_home_m %}
        {% if link %}
            <a href="{{link}}"><img src="{{ads_home_m}}" class="w-100 m" /></a>
        {% else %}
            <img src="{{ads_home_m}}" class="w-100 m" />
        {% endif %}
    {% endif %}

{% endif %}

src/ProjectBundle/Resources/views/Lazboy/Main/_email.html.twig
Hi,<br/><br/>

{{subject}}.<br/>
Message details: <br/><br/>

Name: {{data.name}}<br/>
Email: {{data.email}}<br/>
Phone: {{data.telephoneNumber}}<br/>
Message: <br/>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{data.message|nl2br}}<br/><br/><br/>

<a href="{{ urls }}">View this message</a><br/><br/>

Automatically generated email<br/>
La-Z-Boy Thailand

src/ProjectBundle/Resources/views/Lazboy/Main/_email_order_status.html.twig
{% extends "ProjectBundle:Lazboy:layout_email.html.twig" %}

{% block content %}
    <!--[if gte mso 9]>
        <v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t">
            <v:fill type="tile" color="#eeeeee"></v:fill>
        </v:background>
    <![endif]-->
    <table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0" border="0">
        <tbody>
            <tr>
                <td colspan="3" class="esd-block-image es-p25t es-p25b es-p35r es-p35l">
                    {{ body|raw }}
                    <br/>
                </td>
            </tr>

            {#
            <tr>
                <td colspan="3" class="esd-block-text es-p15t es-p20b" align="left">
                    Order Number #{{ order.ordernumber }}<br/>
                </td>
            </tr>
            #}

            <tr style="background-color:#D3D3D3;">
                <td colspan="2" align="center">
                    <h4>{% trans from "messages" into tran_locale %}order.items{% endtrans %} ({% trans from "messages" into tran_locale %}order.qty{% endtrans %})</h4>
                </td>
                <td >
                    <h4>{% trans from "messages" into tran_locale %}order.price{% endtrans %}</h4>
                </td>
            </tr>
            {% for order_item in order_items %}
                <tr>
                    <td width="16%" style="padding: 5px 10px 5px 0" >
                        <p>
                            {% if order_item.image %}
                                <img src="{{order_item.image|imagine_filter('img_product_small')}}" alt="" style="" width="50px;"/>
                            {% endif %}
                        </p>
                    </td>
                    <td  align="left">
                        <p>
                            {{order_item.productTitle}} ({{order_item.quantity}})

                            {% if order_item.preOrderStatus %}
                                <span class="badge badge-primary"><small>{% trans from "messages" into tran_locale %}order.pre_order{% endtrans %}</small></span>
                            {% elseif order_item.preOrderStatus == 0 and order_item.inventoryPolicyStatus %}
                                <span class="badge badge-primary"><small>{% trans from "messages" into tran_locale %}order.instock{% endtrans %}</small></span>
                            {% endif %}

                            <br/><small>
                                {% if order_item.productCategoryTitle %}
                                    {{order_item.productCategoryTitle}}
                                {% endif %}
                                {% if order_item.skuTitle|length > 0 %}
                                    {{ order_item.skuTitle|join(' · ') }}
                                {% endif %}
                            </small>

                            {% if order_item.skuValue %}
                                <br/>
                                <small>SKU:&nbsp;{{order_item.skuValue}}</small>
                            {% endif %}
                        </p>

                        {% if order_item.customerOrderItemOptions|length > 0 %}
                            <div style="font-size: 13px;">
                                <span>Options {% if order_item.sumOptionsPrice>0 %} ({% trans from "messages" into tran_locale %}total{% endtrans %} ฿{{order_item.sumOptionsPrice|number_format(0, '.', ',')}}) {% endif %}</span>
                                <ul style="padding-left:18px;">
                                    {% for customer_order_item_option in order_item.customerOrderItemOptions %}
                                        <li style="font-size:12px; list-style-type:disc; display:list-item">
                                            <span>&nbsp;{{customer_order_item_option.optionCategoryTitle}}:</span>
                                            <span>{{customer_order_item_option.optionTitle}}</span>
                                            {% if customer_order_item_option.optionPrice>0 %}
                                                <span>(+฿{{customer_order_item_option.optionPrice}})</span>
                                            {% endif %}
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </td>

                    <td width="20%" style="padding: 5px 0"  align="left">
                        <p>฿{{order_item.amount|number_format(0, '.', ',')}}</p>
                    </td>
                </tr>
            {% endfor %}

            <tr>
                <td colspan="2" style="padding: 5px 10px 5px 0"  align="left">
                    <p>{% trans from "messages" into tran_locale %}order.shipping_fee{% endtrans %}</p>
                </td>
                <td style="padding: 5px 0" align="left">
                    <p>
                        ฿{{order.shippingCost|number_format(0, '.', ',') }}
                        {#{% if order.shippingCost > 0 %}
                            ฿{{order.shippingCost|number_format(0, '.', ',') }}
                        {% else %}
                            Free Shipping
                        {% endif %}#}
                    </p>
                </td>
            </tr>

            {% if order.discountAmount %}
                <tr>
                    <td colspan="2" style="padding: 5px 10px 5px 0" align="left">
                        <p>{% trans from "messages" into tran_locale %}order.promotion{% endtrans %} {% if order.discountCode %} Code: {{order.discountCode}}{% endif %}</p>
                    </td>
                    <td style="padding: 5px 0" align="left">
                        <p>-฿{{order.discountAmount|number_format(0, '.', ',') }}</p>
                    </td>
                </tr>
            {% endif %}

            <tr style="border-top: 3px solid rgb(238, 238, 238); border-bottom: 3px solid rgb(238, 238, 238);">
                <td colspan="2" style="border-top: 3px solid rgb(238, 238, 238); border-bottom: 3px solid rgb(238, 238, 238); padding-top: 7px;">
                    <h4>{% trans from "messages" into tran_locale %}order.total{% endtrans %}</h4>
                </td>
                <td style="border-top: 3px solid rgb(238, 238, 238); border-bottom: 3px solid rgb(238, 238, 238); padding-top: 7px;">
                    <h4>฿{{order.totalPrice|number_format(0, '.', ',') }}</h4>
                </td>
            </tr>

            {% if order_status == payment_status_paid or order_status == payment_status_shipped or order_status == payment_status_delivered  %}
                <tr>
                    <td colspan="3">
                        <div class="group">
                            <div class="col-left">
                                <br/>
                                <h4>Shipping To</h4>
                                {% for orderDeliverys in order.customerOrderDeliverys %}
                                    {% if orderDeliverys.addressType == 1 %}
                                        <p>
                                            {{orderDeliverys.firstName}} {{orderDeliverys.lastName}}
                                            {% if orderDeliverys.companyName %}<br />{{orderDeliverys.companyName}}{% endif %}
                                            {% if orderDeliverys.headOffice %}&nbsp;&nbsp;({{orderDeliverys.headOffice}}){% endif %}<br/><br/>
                                            {{orderDeliverys.address}}, {{orderDeliverys.district}}, {{orderDeliverys.amphure}}<br />
                                            {{orderDeliverys.province}} {{orderDeliverys.postCode}}<br />
                                            Phone {{orderDeliverys.phone}}
                                        </p>
                                    {% endif %}
                                {% else %}
    	                            No data
    	                        {% endfor %}
                            </div>

                        </div>
                    </td>
                </tr>
            {% endif %}

            <tr>
                <td colspan="3">
                    <div class="group">

                        {% if order_status == payment_status_delivered %}
                            <div class="col-left">
                                {% if order.shipDate %}
                                    <br/>
                                    <h4>Delivered on</h4>
                                    <div class="panel panel-default">
                                        <div class="panel-body" align="center">
                                            <h5>&nbsp;</h5>
                                            <h3 class="text-warning">{{order.shipDate|date("d F Y")}}</h3>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}

                        {% if order_status == payment_status_shipped %}
                            <div class="col-left">
                                {% if order.shipDate %}
                                    <br/>
                                    <h4>Estimated Delivery Date</h4>
                                    <div class="panel panel-default">
                                        <div class="panel-body" align="center">
                                            <h5>&nbsp;</h5>
                                            <h3 class="text-warning">{{order.shipDate|date("d F Y")}}</h3>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}

                        {% if order_status == payment_status_paid %}
                            <div class="col-right">
                                <br/>
                                 <h4>Payment Method</h4>
                                 <div class="panel panel-default">
                                     <div class="panel-body" align="center">
                                        {% if order.paymentOption == payment_bank_transfer_code %}
                                                <h5> {{order.paymentOptionTitle|trans({}, 'messages', tran_locale)}} </h5>
                                            {% if order.paid == 0 %}
                                                <h3 class="text-warning">{{payment_status_awaiting_payment|trans({}, 'messages', tran_locale)}}</h3>
                                            {% else %}
                                                <h3 class="text-success">{{payment_status_paid|trans({}, 'messages', tran_locale)}}</h3>
                                            {% endif %}

                                        {% elseif order.paymentOption == payment_omise_code %}
                                            <!-- CRDT -->
                                            {% set payment_omise = order.customerPaymentOmise %}

                                            <h5> {{order.paymentOptionTitle|trans({}, 'messages', tran_locale)}} </h5>
                                            {% if payment_omise.status == payment_status_failed  %}
                                                <h3 class="text-warning">{{payment_status_failed|trans({}, 'messages', tran_locale)}}</h3>
                                            {% else %}
                                                <h3 class="text-success">{{payment_status_paid|trans({}, 'messages', tran_locale)}}</h3>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                 </div>
                             </div>
                         {% endif %}

                     </div>
                </td>
            </tr>

        </tbody>
    </table>
{% endblock %}

src/ProjectBundle/Resources/views/Lazboy/Main/_email_payment_bank_transfer.html.twig
{% extends "ProjectBundle:Lazboy:layout_email.html.twig" %}

{% block content %}

Hello Admin,<br/><br/>

You have a new message in bank transfer.<br/><br/>

Customer Name: {{payment_bank_transfer.firstName}} {{payment_bank_transfer.lastName}}<br/>
Email: {{user.email}}<br/>
Phone Number: {{payment_bank_transfer.phone}}<br/>

Bank Account: {{bank_account.title}}<br/>
Amout: ฿{{payment_bank_transfer.amount|number_format(0, '', ',')}}<br/>

Order Number: {{customer_order.orderNumber}}<br/>
Date Transfer: {{payment_bank_transfer.dateTransfer|date('d/m/Y')}} {{payment_bank_transfer.timeTransfer|date('H:i')}}<br/>

{% if payment_bank_transfer.attachfile %}
	Attach File : <a href="{{ url('admin_customer_payment_bank_transfer_download',{'id': payment_bank_transfer.id}) }}">Download</a>
{% endif %}

<br/><br/>
Automatically generated email<br/>
La-Z-Boy Thailand

{% endblock %}

src/ProjectBundle/Resources/views/Lazboy/Main/_email_product_review.html.twig
Dear Administrator, <br/><br/>

You have just received afollowing customer review for <b>{{product.getTitle}}</b> <br/><br/>

Please log in to <a href="{{ admin_panel_url }}">admin panel</a> to approve the product review to show the review on the website. <br/><br/>

Customer Name : {{review.reviewername}} <br/><br/>
Rating : {% for i in 1 .. review.ratingScore %}&#9733{% endfor %}<br/><br/>
Review Title : {{review.getTitle}} <br/><br/>
Review Detail : {{review.getContent|nl2br}} <br/><br/>

<br/>
Thank you, <br/>
Automatically generated email <br/>

src/ProjectBundle/Resources/views/Lazboy/Main/_footer_contacts.html.twig
<ul class="list-xs">
    {% if contact_address.optionValue %}
        <li>
            <dl class="list-terms-minimal">
                <dt>{% trans %}contact.address{% endtrans %}</dt>
                <dd>
                    {{contact_address.optionValue}}
                </dd>
            </dl>
        </li>
    {% endif %}

    {% if contact_phone.optionValue %}
        <li>
            <dl class="list-terms-minimal">
                <dt>{% trans %}contact.phone{% endtrans %}</dt>
                <dd>
                    <ul class="list-semicolon">
                        <li>
                            <a href="tel:{{contact_phone.optionValue|telFilter}}">{{contact_phone.optionValue}}</a>
                        </li>
                    </ul>
                </dd>
            </dl>
        </li>
    {% endif %}

    {% if contact_fax.optionValue %}
        <li>
            <dl class="list-terms-minimal">
                <dt>{% trans %}contact.fax{% endtrans %}</dt>
                <dd>
                    <ul class="list-semicolon">
                        <li>
                            {{contact_fax.optionValue}}
                        </li>
                    </ul>
                </dd>
            </dl>
        </li>
    {% endif %}

    {% if contact_email.optionValue %}
        <li>
            <dl class="list-terms-minimal">
                <dt>{% trans %}contact.email{% endtrans %}</dt>
                <dd>
                    <a href="mailto:{{contact_email.optionValue}}">{{contact_email.optionValue}}</a>
                </dd>
            </dl>
        </li>
    {% endif %}

    {% if contact_business_hours.optionValue %}
        <li>
            <dl class="list-terms-minimal">
                <dt>{% trans %}contact.open{% endtrans %}</dt>
                <dd>{{contact_business_hours.optionValue}}</dd>
            </dl>
        </li>
    {% endif %}
</ul>

src/ProjectBundle/Resources/views/Lazboy/Main/email_test.html.twig
{% extends "ProjectBundle:"~ view_layout ~":layout_email.html.twig" %}

{% block content %}
--------
{% endblock %}

src/ProjectBundle/Resources/views/Lazboy/Main/faq.html.twig
{% extends "ProjectBundle:"~ view_layout ~":layout.html.twig" %}

{% block title %}{% trans %}menu.faq{% endtrans %} | {{ parent() }}{% endblock %}
{% block faq_active %}active{% endblock %}

{% block breadcrumbs_title %}{% trans %}faq.frequently{% endtrans %}{% endblock %}
{% block breadcrumbs_custom %}
	<li class="active">{% trans %}menu.faq{% endtrans %}</li>
{% endblock %}

{% block content %}
<section class="pt-4 pb-5 bg-default">
	<div class="container">
		<!-- Accordion-->
		<div id="accordion" role="tablist">
			<!-- Bootstrap panel-->
			{% for data in paginated.currentpageresults %}
			<div class="panel panel-custom">
				<div class="panel-custom-heading" id="{{data.id}}Headingundefined" role="tab">
					<h5 class="panel-custom-title">
						<a class="collapsed" role="button" data-toggle="collapse" data-parent="#{{data.id}}" href="#{{data.id}}Collapseundefined" aria-controls="{{data.id}}Collapseundefined">
							{{data.getTitle}}
						</a>
					</h5>
				</div>
				<div class="panel-custom-collapse collapse" id="{{data.id}}Collapseundefined" role="tabpanel" aria-labelledby="{{data.id}}Headingundefined">
					<div class="panel-custom-body">
						{{data.getShortDesc|nl2br}}
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>

{% if paginated.havetopaginate %}
<!-- Divider-->
<div class="container">
	<div class="divider"></div>
</div>

<section class="section-sm text-center">
	<div class="container">
		<!-- Classic Pagination-->
		<nav>
			{{pagerfanta(paginated,'twitter_bootstrap3_translated_lazboy')}}
		</nav>
	</div>
</section>
{% endif %}

{% endblock %}

src/ProjectBundle/Resources/views/Lazboy/Main/history.html.twig
{% extends "ProjectBundle:"~ view_layout ~":layout.html.twig" %}

{% block title %}{{data.getTitle}} - {% trans %}menu.history{% endtrans %} | {{ parent() }}{% endblock %}
{% block history_active %}active{% endblock %}

{% block breadcrumbs_title %}{% trans %}menu.history{% endtrans %}{% endblock %}
{% block breadcrumbs_custom %}
	<li><a href="{{path('history')}}">{% trans %}menu.history{% endtrans %}</a></li>
	<li class="active">{{data.getTitle}}</li>
{% endblock %}

{% block content %}
<section class="bg-default pt-4 pb-5">
    <div class="container">
		<div class="row row-70 justify-content-sm-center">

			<div class="col-lg-7 col-xl-8 section-divided__main">
				{% if data.image %}
				<figure class="figure mb-3">
					<img src="{{asset(data.image) | imagine_filter('img_w_1000')}}" alt="{{data.getTitle}}" />
				</figure>
				{% endif %}
				{% if app.request.locale == "en" %}
					{% set css_font_size = "font-size-14" %}
				{% elseif app.request.locale == "th" %}
					{% set css_font_size = "font-size-16" %}
				{% endif %}
				<div class="{{css_font_size}}">
					{{data.getDescription|raw}}
				</div>
			</div>

			<div class="col-lg-5 col-xl-4 section-divided__aside section-divided__aside-left">
				<section class="section-sm">
					<h5>History</h5>
					<ul class="list-linked">
					{% if historys|length > 0 %}
						{% for history in historys %}
						<li><a href="{{path('history_detail',{'id':history.id,'slug':history.getTitle|slug})}}" {% if history.id == data.id %}style="color:#2969b0;"{% endif %}>{{history.getTitle}}</a></li>
						{% endfor %}
					{% endif %}
					</ul>
				</section>

				{% include 'ProjectBundle:'~ view_layout ~'/Main:_social.html.twig' %}

			</div>

		</div>
    </div>
</section>
{% endblock %}